Repository pure-data/pure-data, pull requests merged in 2020-08, with the labels that each got.

#1119 disable dark mode for GUI on macOS 10.14+
  mac/README.txt
  tcl/pd_guiprefs.tcl
Labels: bug/fix, subject:GUI

#1120 set canvas background color for macOS and newer Tk versions
  tcl/pdtk_canvas.tcl
Labels: bug/fix, subject:GUI

#779 exitcode
  src/m_glob.c
  src/m_imp.h
  src/s_inter.c
Labels: feature

#841 several gpointer bugfixes
  src/m_binbuf.c
  src/m_class.c
  src/x_connective.c
  src/x_interface.c
Labels: bug/fix

#815 only send rtext-data if there's an actual window to send it to
  src/g_rtext.c
Labels: bug/fix
