Repository pure-data/pure-data, pull requests merged in 2021-07, with the labels that each got.

#855 soundfile updates: refactor, bugfixes, AIFC, & CAF
  README.txt
  doc/5.reference/readsf~-help.pd
  doc/5.reference/soundfiler-help.pd
  doc/5.reference/writesf~-help.pd
  src/Makefile.am
  src/d_soundfile.c
  src/d_soundfile.h
  src/d_soundfile_aiff.c
  src/d_soundfile_caf.c
  src/d_soundfile_next.c
  src/d_soundfile_wave.c
  src/g_array.c
  src/makefile.gnu
  src/makefile.mac
  src/makefile.mingw
  src/makefile.msvc
Labels: bug/fix, feature, subject:code-cleanup, subject:core

#989 Draw array name when creating a garray
  src/g_array.c
Labels: bug/fix

#965 improve find and error tracking
  src/g_clone.c
  src/g_editor.c
  src/g_text.c
  src/m_binbuf.c
Labels: feature

#937 finally save iemguis colors as hex symbols
  src/g_all_guis.c
Labels: improvement

#192 Untitled filename keyword
  src/g_canvas.c
  src/g_canvas.h
  src/g_readwrite.c
  tcl/pd_menucommands.tcl
  tcl/pd_menus.tcl
  tcl/pdtk_canvas.tcl
Labels: bug/fix

#464 trackable print
  src/m_pd.h
  src/s_print.c
  src/x_interface.c
Labels: feature

#519 include libpd
  configure.ac
  src/Makefile.am
  src/s_libpdmidi.c
  src/x_libpdreceive.c
  src/x_libpdreceive.h
  src/z_hooks.c
  src/z_hooks.h
  src/z_libpd.c
  src/z_libpd.h
  src/z_print_util.c
  src/z_print_util.h
  src/z_queued.c
  src/z_queued.h
  src/z_ringbuffer.c
  src/z_ringbuffer.h
Labels: feature

#594 add more methods to [list store]
  doc/5.reference/list-help.pd
  src/x_list.c
Labels: feature

#767 improve (verbose) logging
  src/m_class.c
  src/m_pd.h
  src/s_audio.c
  src/s_audio_alsa.c
  src/s_audio_jack.c
  src/s_audio_mmio.c
  src/s_audio_oss.c
  src/s_audio_pa.c
  src/s_file.c
  src/s_inter.c
  src/s_main.c
  src/s_midi.c
  src/s_midi_oss.c
  src/s_midi_pm.c
  src/s_path.c
Labels: improvement
