Repository pure-data/pure-data, pull requests merged in 2021-12, with the labels that each got.

#1485 updated libpd and test_libpd
  .gitignore
  Makefile.am
  libpd/Makefile
  libpd/README.txt
  libpd/makefile
  libpd/makefile.example
  libpd/test_libpd.pd
  libpd/test_libpd/Makefile
  libpd/test_libpd/test_libpd.c
  libpd/test_libpd/test_libpd.pd
Labels: improvement, subject:libpd

#836 [WIP] multi-instance hook update
  src/m_class.c
  src/s_print.c
  src/s_stuff.h
Labels: feature, subject:libpd

#1496 [0.52-test$] html
  doc/1.manual/x4.htm
Labels: documentation

#1510 [ci] add GitHub workflow
  .github/workflows/puredata.yml
Labels: improvement
