Repository pure-data/pure-data, pull requests merged in 2023-06, with the labels that each got.

#1907 stable development branch
  extra/pd~/pdsched.c
  mac/README.txt
  msw/build-nsi.sh
  msw/installer-art/big.bmp
  msw/installer-art/small.bmp
  msw/pd.nsi
  src/d_global.c
  src/g_all_guis.c
  src/g_slider.c
  src/g_template.c
  src/s_audio_jack.c
  src/s_inter.c
  tcl/dialog_font.tcl
  tcl/dialog_iemgui.tcl
  tcl/pd_docsdir.tcl
  tcl/pdwindow.tcl
Labels: bug/fix, crash, documentation, subject:GUI, subject:core, os:windows

#1605 filename extensions for double-precision externals (and removing system-specific quirks)
  .gitignore
  INSTALL.txt
  configure.ac
  doc/1.manual/index.htm
  doc/1.manual/x6-c.htm
  doc/1.manual/x6.htm
  extra/pd~/GNUmakefile.am
  extra/pd~/makefile
  extra/pd~/pdsched.c
  extra/pd~/pd~.c
  mac/osx-app.sh
  portaudio/Makefile.am
  src/Makefile.am
  src/d_array.c
  src/d_fft_fftsg.c
  src/d_osc.c
  src/g_all_guis.c
  src/g_bang.c
  src/g_canvas.c
  src/g_clone.c
  src/g_editor.c
  src/m_binbuf.c
  src/m_class.c
  src/m_glob.c
  src/m_obj.c
  src/m_private_utils.h
  src/m_sched.c
  src/makefile.gnu
  src/makefile.mac
  src/makefile.mingw
  src/s_audio.c
  src/s_audio_alsa.c
  src/s_audio_oss.c
  src/s_audio_pa.c
  src/s_file.c
  src/s_inter.c
  src/s_loader.c
  src/s_main.c
  src/s_net.h
  src/s_path.c
  src/s_print.c
  src/s_stuff.h
  src/s_utf8.c
  src/x_array.c
  src/x_file.c
  src/x_gui.c
  src/x_list.c
  src/x_misc.c
  src/x_net.c
  src/x_text.c
  src/x_vexp_fun.c
Labels: subject:API, improvement

#1929 enlarge hot area for outlets
  src/g_editor.c
Labels: subject:patching, improvement

#1762 improve [pack] reentrancy handling
  src/x_connective.c
Labels: subject:core, improvement

#1590 [file] new verbs 'isabsolute', 'normalize', 'cwd', 'patchpath'
  doc/5.reference/file-help.pd
  src/x_file.c
Labels: feature, improvement

#1064 add "-open-with-args" command line option
  src/s_main.c
Labels: feature

#2015 Update translations
  po/az.po
  po/bg.po
  po/de.po
  po/el.po
  po/en.po
  po/en_ca.po
  po/es.po
  po/eu.po
  po/fr.po
  po/gu.po
  po/he.po
  po/hi.po
  po/hu.po
  po/id.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nl.po
  po/pa.po
  po/pl.po
  po/pt_br.po
  po/pt_pt.po
  po/ru.po
  po/sq.po
  po/sv.po
  po/template.pot
  po/uk.po
  po/vi.po
  po/zh_tw.po
Labels: subject:GUI, improvement

#2031 Update translations
  po/az.po
  po/bg.po
  po/de.po
  po/el.po
  po/en.po
  po/en_ca.po
  po/es.po
  po/eu.po
  po/fr.po
  po/gu.po
  po/he.po
  po/hi.po
  po/hu.po
  po/id.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nl.po
  po/pa.po
  po/pl.po
  po/pt_br.po
  po/pt_pt.po
  po/ru.po
  po/sq.po
  po/sv.po
  po/template.pot
  po/uk.po
  po/vi.po
  po/zh_tw.po
Labels: subject:GUI, improvement
