Repository pure-data/pure-data, pull requests merged in 2024-08, with the labels that each got.

#2360 stable development branch
  src/d_resample.c
  src/s_inter_gui.c
  tcl/dialog_array.tcl
  tcl/pd-gui.tcl
  tcl/pd_bindings.tcl
  tcl/pd_menucommands.tcl
  tcl/wheredoesthisgo.tcl
Labels: bug/fix, regression, subject:GUI

#2408 stable development branch
  src/x_vexp.h
  src/x_vexp_fun.c
Labels: os:windows, subject:build-system

#2397 Documentation updates
  doc/5.reference/array-object-help.pd
  doc/5.reference/canvas-help.pd
  doc/5.reference/cos~-help.pd
  doc/5.reference/expr-help.pd
  doc/5.reference/file-help.pd
  doc/5.reference/gui-boxes-help.pd
  doc/5.reference/makefilename-help.pd
  doc/5.reference/osc-format-parse-help.pd
  doc/5.reference/osc~-help.pd
  doc/5.reference/pd-messages.pd
  doc/5.reference/route-help.pd
  doc/5.reference/savepanel-help.pd
  doc/5.reference/soundfiler-help.pd
  doc/5.reference/symbol-help.pd
  doc/5.reference/tabwrite-help.pd
  doc/5.reference/text-object-help.pd
  doc/5.reference/vcf~-help.pd
  doc/8.topics/expr.htm
  src/x_vexp.c
Labels: documentation

#2413 stable development branch
  src/s_inter.c
Labels: bug/fix, os:windows, subject:build-system
