Repository pure-data/pure-data, pull requests merged in 2024-03, with the labels that each got.

#2125 stable development branch
  extra/pd~/pdsched.c
  linux/org.puredata.pd-gui.metainfo.xml
  msw/pd.nsi
  src/d_fft_fftsg.c
  src/d_fft_fftw.c
  src/d_global.c
  src/d_soundfile.c
  src/d_ugen.c
  src/g_all_guis.c
  src/g_all_guis.h
  src/g_bang.c
  src/g_canvas.c
  src/g_editor.c
  src/g_io.c
  src/g_mycanvas.c
  src/g_numbox.c
  src/g_radio.c
  src/g_slider.c
  src/g_text.c
  src/g_toggle.c
  src/g_vumeter.c
  src/m_class.c
  src/m_glob.c
  src/m_imp.h
  src/m_obj.c
  src/m_pd.c
  src/m_pd.h
  src/m_sched.c
  src/s_inter.c
  src/s_inter_gui.c
  src/s_midi_pm.c
  src/s_print.c
  src/s_stuff.h
  src/x_gui.c
  src/x_list.c
  src/x_midi.c
  tcl/dialog_font.tcl
  tcl/dialog_preferences.tcl
  tcl/pdtk_canvas.tcl
  tcl/pdwindow.tcl
  tcl/wheredoesthisgo.tcl
Labels: bug/fix, subject:core

#2145 Import deken v0.9.18
  tcl/pd_deken.tcl
Labels: bug/fix, crash, os:macOS, os:windows

#2160 Various minor improvements to [file]
  src/x_file.c
Labels: bug/fix, subject:core, improvement

#2158 Safe cross-platform `snprintf` and `vsnprintf` alternative
  extra/pd~/pd~.c
  src/g_all_guis.c
  src/g_canvas.c
  src/m_binbuf.c
  src/m_class.c
  src/m_obj.c
  src/m_private_utils.h
  src/s_audio_mmio.c
  src/s_audio_pa.c
  src/s_file.c
  src/s_inter.c
  src/s_loader.c
  src/s_print.c
  src/s_stuff.h
  src/x_file.c
  src/x_gui.c
Labels: bug/fix, subject:core, improvement

#2165 fix `pd_this` on Windows
  src/m_class.c
  src/m_pd.h
Labels: bug/fix, subject:API

#688 Emscripten support for libpd
  src/Makefile.am
  src/d_osc.c
  src/d_ugen.c
  src/m_class.c
  src/m_class_dispatcher.c
  src/m_class_dispatcher_1.h
  src/m_class_dispatcher_2.h
  src/m_imp.h
  src/m_pd.c
  src/s_inter.c
  src/x_connective.c
  src/x_list.c
  src/x_misc.c
Labels: improvement
