Repository pure-data/pure-data, pull requests merged in 2024-10, with the labels that each got.

#2433 stable development branch
  INSTALL.txt
  src/d_osc.c
  src/m_private_utils.h
  src/s_audio_jack.c
  src/s_loader.c
  src/x_vexp_if.c
  src/z_ringbuffer.c
  tcl/pd-gui.tcl
  tcl/pd_deken.tcl
  tcl/pd_docsdir.tcl
Labels: severity:bug/fix, severity:crash, severity:regression, subject:expr

#2434 Documentation Updates
  INSTALL.htm
  doc/1.manual/index.htm
  doc/1.manual/resources/chapter2.htm
  doc/2.control.examples/04.messages.pd
  doc/2.control.examples/16.more.arrays.pd
  doc/3.audio.examples/D10.sampler.notes.pd
  doc/3.audio.examples/D11.sampler.poly.pd
  doc/3.audio.examples/F03.pulse.spectrum.pd
  doc/5.reference/array-object-help.pd
  doc/5.reference/canvas-help.pd
  doc/5.reference/expr-help.pd
  doc/5.reference/float-help.pd
  doc/5.reference/osc-format-parse-help.pd
  doc/5.reference/readsf~-help.pd
  doc/5.reference/route-help.pd
  doc/5.reference/soundfiler-help.pd
  doc/5.reference/vcf~-help.pd
  doc/5.reference/writesf~-help.pd
  doc/8.topics/expr.htm
  extra/sigmund~/sigmund~-help.pd
Labels: severity:bug/fix, subject:documentation

#2439 add 'clear' message to [vcf~]
  src/d_osc.c
Labels: severity:improvement

#2437 JACK: autoconnections
  src/s_audio_jack.c
Labels: severity:bug/fix, subject:core
