Repository pure-data/pure-data, pull requests merged in 2024-06, with the labels that each got.

#2331 stable development branch
  tcl/pd_guiprefs.tcl
Labels: bug/fix, os:macOS

#2336 doc updates
  doc/5.reference/help-intro.pd
  doc/5.reference/unops-tilde-help.pd
Labels: documentation

#2346 restore old behavior of "quit" message and add new "exit" message
  src/g_editor.c
  src/m_glob.c
  src/m_imp.h
  src/s_inter.c
Labels: bug/fix, regression, subject:patching, subject:core

#2338 stable development branch
  linux/org.puredata.pd-gui.metainfo.xml
  src/Makefile.am
  src/m_pd.h
  src/m_sched.c
Labels: bug/fix, subject:API
