Repository pure-data/pure-data, pull requests merged in 2024-04, with the labels that each got.

#2243 update m_class_dispatcher headers to support up to 6 arguments
  src/Makefile.am
  src/m_class.c
  src/m_class_dispatcher.c
  src/m_class_dispatcher_1.h
  src/m_class_dispatcher_2.h
  src/m_dispatch.h
  src/m_dispatch_gen.c
Labels: bug/fix, subject:core

#2251 stable development branch
  src/d_fft_fftsg.c
  src/d_misc.c
  src/g_graph.c
  src/s_main.c
  src/x_midi.c
Labels: bug/fix, crash, subject:core

#2051 tabread4~: make onset inlet signal rate
  src/d_array.c
Labels: improvement

#2259 stable development branch
  configure.ac
  libpd/Makefile
  src/d_global.c
  src/m_obj.c
  src/makefile.mac
  src/s_inter.c
Labels: bug/fix, subject:core, subject:build-system

#1623 [oscparse] improvements
  src/x_misc.c
Labels: feature
