Repository pure-data/pure-data, pull requests merged in 2024-05, with the labels that each got.

#2279 improve language detection
  mac/osx-app.sh
  tcl/dialog_find.tcl
  tcl/dialog_font.tcl
  tcl/dialog_iemgui.tcl
  tcl/dialog_path.tcl
  tcl/dialog_startup.tcl
  tcl/pd-gui.tcl
  tcl/pd_docsdir.tcl
  tcl/pd_guiprefs.tcl
  tcl/pd_i18n.tcl
  tcl/pd_menucommands.tcl
  tcl/pdtk_canvas.tcl
  tcl/pdtk_textwindow.tcl
  tcl/pdwindow.tcl
  tcl/wheredoesthisgo.tcl
Labels: improvement

#2278 stable development branch
  src/d_soundfile.c
Labels: bug/fix

#2280 Translation updates
  po/pt_br.po
Labels: improvement

#2281 Documentation updates
  doc/5.reference/line~-help.pd
  doc/5.reference/osc-format-parse-help.pd
  doc/5.reference/readsf~-help.pd
  doc/5.reference/send-receive-tilde-help.pd
  doc/5.reference/soundfiler-help.pd
  doc/5.reference/swap-help.pd
  doc/5.reference/throw~-catch~-help.pd
  doc/5.reference/writesf~-help.pd
  src/d_soundfile.c
Labels: documentation

#2210 Windows: restore canvas inside screen bounds
  tcl/pdtk_canvas.tcl
Labels: bug/fix, subject:GUI, os:windows

#2285 stable development branch
  tcl/pdtk_canvas.tcl
Labels: bug/fix, subject:GUI, os:windows

#2293 Update translations
  po/fr.po
  po/pt_br.po
Labels: subject:GUI, improvement

#2304 Documentation updates
  README.txt
  doc/2.control.examples/15.array.pd
  doc/5.reference/array-object-help.pd
  doc/5.reference/loadbang-help.pd
  doc/5.reference/makefilename-help.pd
  doc/5.reference/openpanel-help.pd
  doc/5.reference/readsf~-help.pd
  doc/5.reference/savepanel-help.pd
  doc/5.reference/soundfiler-help.pd
  doc/5.reference/symbol-help.pd
  doc/5.reference/text-object-help.pd
  doc/5.reference/writesf~-help.pd
Labels: documentation

#2306 stable development branch
  doc/5.reference/writesf~-help.pd
  portaudio/README.txt
  portaudio/update.sh
  src/m_glob.c
  src/m_pd.h
Labels: bug/fix, improvement
