Repository pure-data/pure-data, pull requests merged in 2025-01, with the labels that each got.

#2472 fix crash in expr
  src/x_vexp_fun.c
Labels: severity:bug/fix, severity:crash, subject:expr

#2491 stable development branch
  mac/tcltk-wish.sh
  msw/build-nsi.sh
  msw/msw-app.sh
  msw/tcltk-dir.sh
  src/d_soundfile.c
  src/g_io.c
  src/m_binbuf.c
  src/x_connective.c
  tcl/pd_bindings.tcl
  tcl/pd_guiprefs.tcl
  tcl/pd_menucommands.tcl
  tcl/pdtk_canvas.tcl
Labels: severity:bug/fix, severity:crash, subject:GUI, subject:multichannel

#2512 Try to open audio device synchronously
  src/m_sched.c
  src/s_audio.c
  src/s_audio_jack.c
  src/s_audio_pa.c
Labels: severity:bug/fix, severity:regression, subject:core
