Repository pure-data/pure-data, pull requests merged in 2025-05, with the labels that each got.

#2303 new API functions for thread-safe messaging
  src/m_pd.h
  src/m_sched.c
  src/s_inter.c
Labels: severity:feature, subject:API

#2497 Implement missing perform8 methods in d_math.c
  src/d_math.c
Labels: subject:core

#2535 add new API function `pd_findbyclassname`
  src/m_pd.c
  src/m_pd.h
Labels: severity:feature, subject:API

#2052 multichannel support for readsf~ and writesf~
  src/d_soundfile.c
Labels: severity:feature, subject:multichannel

#661 [poly] features
  src/x_midi.c
Labels: severity:feature

#2053 More clone improvements
  src/g_canvas.c
  src/g_clone.c
  src/g_editor.c
  src/g_readwrite.c
Labels: subject:core, severity:improvement

#2548 stable development branch
  extra/fiddle~/fiddle~.c
  src/g_vumeter.c
  src/m_obj.c
  src/x_connective.c
  tcl/pd-gui.tcl
  tcl/pd_bindings.tcl
  tcl/pd_connect.tcl
  tcl/pd_menucommands.tcl
  tcl/pdwindow.tcl
  tcl/preferencewindow.tcl
  tcl/scrollboxwindow.tcl
Labels: severity:bug/fix, severity:crash, subject:GUI, os:macOS

#2547 Import deken v0.10.4
  tcl/pd_deken.tcl
Labels: severity:bug/fix, severity:improvement, os:macOS, os:windows

#2580 stable development branch
  src/g_rtext.c
  tcl/pd_menucommands.tcl
Labels: subject:GUI

#2427 improve garrays: add message to hide name, save properties
  src/d_array.c
  src/g_array.c
  src/g_canvas.c
  src/g_graph.c
  src/g_readwrite.c
Labels: severity:improvement, subject:GUI objects, subject:array

#2595 allow to change the number of channels in table DSP objects
  src/d_array.c
Labels: severity:feature, subject:core, subject:multichannel
