Repository pure-data/pure-data, pull requests merged in 2025-07, with the labels that each got.

#2661 Add missing parenthesis and fix compilation error in current master
  src/g_graph.c
Labels: severity:bug/fix, severity:regression, subject:build-system

#2668 Fix Pd colors
  src/g_bang.c
  src/g_canvas.c
  src/g_editor.c
  src/g_graph.c
  src/g_mycanvas.c
  src/g_numbox.c
  src/g_radio.c
  src/g_scalar.c
  src/g_slider.c
  src/g_toggle.c
  src/g_vumeter.c
Labels: severity:bug/fix

#2666 stable development branch
  src/s_main.c
Labels: severity:bug/fix, os:macOS, os:windows

#2671 Fix Pd colors a bit more
  src/g_all_guis.c
  src/g_all_guis.h
  src/g_bang.c
  src/g_canvas.c
  src/g_canvas.h
  src/g_editor.c
  src/g_graph.c
  src/g_mycanvas.c
  src/g_numbox.c
  src/g_radio.c
  src/g_rtext.c
  src/g_scalar.c
  src/g_slider.c
  src/g_template.c
  src/g_text.c
  src/g_toggle.c
  src/g_vumeter.c
Labels: severity:improvement, subject:GUI objects

#2690 stable development branch
  tcl/dialog_audio.tcl
Labels: subject:GUI

#2704 translation updates
  po/fr.po
  po/hy.po
  po/nl.po
  po/pt_br.po
  po/ru.po
Labels: severity:improvement
