Repository pure-data/pure-data, pull requests merged in 2025-08, with the labels that each got.

#2726 update cords for goprect message
  src/g_graph.c
Labels: severity:bug/fix

#2722 translation updates
  po/Makefile.am
  po/az.po
  po/bg.po
  po/de.po
  po/el.po
  po/en.po
  po/en_ca.po
  po/eo.po
  po/es.po
  po/eu.po
  po/fr.po
  po/gu.po
  po/he.po
  po/hi.po
  po/hu.po
  po/hy.po
  po/id.po
  po/it.po
  po/ja.po
  po/ko.po
  po/nl.po
  po/pa.po
  po/pd_dynamic_strings.tcl
  po/pl.po
  po/pt_br.po
  po/pt_pt.po
  po/ru.po
  po/sq.po
  po/sv.po
  po/ta.po
  po/template.pot
  po/tr.po
  po/uk.po
  po/vi.po
  po/zh_tw.po
Labels: subject:GUI, severity:improvement

#2753 fix ds array init when instantiated template contains arrays or texts
  src/g_scalar.c
Labels: severity:crash
